# DSCI 552 - Homework 3

**Name:** Khushi Patel  
**GitHub Username:** khushigi-a11y  
**USC ID:** 4163615025

In [1]:
import os
import numpy as np
import pandas as pd

## 1. Time Series Classification Part 1: Feature Creation/Extraction

### (a) AReM Dataset

In [2]:
data_path = "data/AReM"

#storing every folder
activities = [
    "bending1",
    "bending2",
    "cycling",
    "lying",
    "sitting",
    "standing",
    "walking"
]
#creating individual path for each file
for activity in activities:
    folder_path = f"{data_path}/{activity}"
    
    csv_files = []
    
    for file in os.listdir(folder_path):
        if file.endswith(".csv"):
            csv_files.append(file)
    #print how many files r in the list
    print(activity, len(csv_files))

bending1 7
bending2 6
cycling 15
lying 15
sitting 15
standing 15
walking 15

In [3]:
# Stores training and testing paths
train_files = []
test_files = []

for activity in activities:
    folder_path = f"{data_path}/{activity}"
    
    # Getting all the CSV files in the folder
    csv_files = [
        file for file in os.listdir(folder_path)
        if file.endswith(".csv")
    ]
    
    for file in csv_files:
        file_path = f"{folder_path}/{file}"
        
        #assigning the datasets 1 and 2 as the test data
        if activity in ["bending1", "bending2"]:
            if file in ["dataset1.csv", "dataset2.csv"]:
                test_files.append(file_path)
            else:
                train_files.append(file_path)
        
        #assigning datasets 1, 2, and 3 as the test data
        else:
            if file in ["dataset1.csv", "dataset2.csv", "dataset3.csv"]:
                test_files.append(file_path)
            else:
                train_files.append(file_path)

#the number of train and test instances
print("Training instances:", len(train_files))
print("Testing instances:", len(test_files))
print("Total instances:", len(train_files) + len(test_files))

Training instances: 69
Testing instances: 19
Total instances: 88

### (c) Feature Extraction

#### (i) Time-Domain Features

Common time-domain features used in time series classification include:

- Minimum
- Maximum
- Mean
- Median
- Standard deviation
- Variance
- First quartile (Q1)
- Third quartile (Q3)
- Interquartile range (IQR)
- Range
- Root mean square (RMS)
- Skewness
- Kurtosis
- Zero-crossing rate

In [4]:
sample_path = "data/AReM/bending1/dataset1.csv"

sample_df = pd.read_csv(
    sample_path,
    skiprows=4
)

sample_df.head()

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,39.25,0.43,22.75,0.43,33.75,1.3
1,250,39.25,0.43,23.00,0.00,33.00,0.0
2,500,39.25,0.43,23.25,0.43,33.00,0.0
3,750,39.50,0.50,23.00,0.71,33.00,0.0
4,1000,39.50,0.50,24.00,0.00,33.00,0.0

In [5]:
sample_df.shape

(480, 7)

#### (ii) Extraction of Time-Domain Features

For each of the six time series in every instance, the following seven features are extracted: minimum, maximum, mean, median, standard deviation, first quartile, and third quartile.

In [6]:
# Six time series columns from each dataset
time_series_columns = [
    "avg_rss12",
    "var_rss12",
    "avg_rss13",
    "var_rss13",
    "avg_rss23",
    "var_rss23"
]

# Extracting the features 
def extract_features(file_path):
    
    # Reading the CSV file
    df = pd.read_csv(
        file_path,
        skiprows=4,
        usecols=range(7)
    )

    features = []

    # Going through each of the 6 time series
    for column in time_series_columns:
        series = df[column]

        # Adding the required features
        features.extend([
            series.min(),
            series.max(),
            series.mean(),
            series.median(),
            series.std(),
            series.quantile(0.25),
            series.quantile(0.75)
        ])

    return features

In [7]:
sample_features = extract_features(sample_path)

print("Number of features:", len(sample_features))
print(sample_features)

Number of features: 42
[np.float64(37.25), np.float64(45.0), np.float64(40.62479166666667), np.float64(40.5), np.float64(1.4769669162668115), np.float64(39.25), np.float64(42.0), np.float64(0.0), np.float64(1.3), np.float64(0.35860416666666667), np.float64(0.43), np.float64(0.32260475889665613), np.float64(0.0), np.float64(0.5), np.float64(4.0), np.float64(29.5), np.float64(19.0409375), np.float64(19.25), np.float64(4.462951988916728), np.float64(16.0), np.float64(23.25), np.float64(0.0), np.float64(7.23), np.float64(0.8325416666666666), np.float64(0.5), np.float64(0.9656588815438522), np.float64(0.0), np.float64(1.12), np.float64(27.25), np.float64(38.25), np.float64(34.31129166666666), np.float64(35.0), np.float64(2.188448606924462), np.float64(33.0), np.float64(36.0), np.float64(0.0), np.float64(1.92), np.float64(0.5705833333333333), np.float64(0.43), np.float64(0.5829154940538743), np.float64(0.0), np.float64(1.3)]

In [8]:
feature_names = []

for i in range(1, 7):
    feature_names.extend([
        f"min{i}",
        f"max{i}",
        f"mean{i}",
        f"median{i}",
        f"std{i}",
        f"1st_quart{i}",
        f"3rd_quart{i}"
    ])

print(feature_names)
print("Number of columns:", len(feature_names))

['min1', 'max1', 'mean1', 'median1', 'std1', '1st_quart1', '3rd_quart1', 'min2', 'max2', 'mean2', 'median2', 'std2', '1st_quart2', '3rd_quart2', 'min3', 'max3', 'mean3', 'median3', 'std3', '1st_quart3', '3rd_quart3', 'min4', 'max4', 'mean4', 'median4', 'std4', '1st_quart4', '3rd_quart4', 'min5', 'max5', 'mean5', 'median5', 'std5', '1st_quart5', '3rd_quart5', 'min6', 'max6', 'mean6', 'median6', 'std6', '1st_quart6', '3rd_quart6']
Number of columns: 42

In [9]:
# Combining all training and testing files
all_files = train_files + test_files

all_features = []

# Extracting the features
for file_path in all_files:
    features = extract_features(file_path)
    all_features.append(features)

# Creating a Df with all extracted features
feature_df = pd.DataFrame(
    all_features,
    columns=feature_names
)

feature_df.index = range(1, len(feature_df) + 1)
feature_df.index.name = "Instance"

feature_df

,min1,max1,mean1,median1,std1,1st_quart1,3rd_quart1,min2,max2,mean2,...,std5,1st_quart5,3rd_quart5,min6,max6,mean6,median6,std6,1st_quart6,3rd_quart6
Instance,,,,,,,,,,,,,,,,,,,,,
1,36.25,48.00,43.969125,44.500,1.618364,43.31,44.6700,0.0,1.50,0.413125,...,3.318301,20.5000,23.750,0.0,2.96,0.555312,0.490,0.487826,0.000,0.830
2,37.00,48.00,43.454958,43.250,1.386098,42.50,45.0000,0.0,1.58,0.378083,...,2.488862,22.2500,24.000,0.0,5.26,0.679646,0.500,0.622534,0.430,0.870
3,33.00,47.75,42.179812,43.500,3.670666,39.15,45.0000,0.0,3.00,0.696042,...,3.849448,30.4575,36.330,0.0,2.18,0.613521,0.500,0.524317,0.000,1.000
4,33.00,45.75,41.678063,41.750,2.243490,41.33,42.7500,0.0,2.83,0.535979,...,2.411026,28.4575,31.250,0.0,1.79,0.383292,0.430,0.389164,0.000,0.500
5,35.00,47.40,43.954500,44.330,1.558835,43.00,45.0000,0.0,1.70,0.426250,...,1.999604,35.3625,36.500,0.0,1.79,0.493292,0.430,0.513506,0.000,0.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,35.50,46.25,43.174938,43.670,1.989052,42.50,44.5000,0.0,2.12,0.506583,...,2.983976,12.7500,16.500,0.0,5.72,0.911979,0.830,0.666161,0.470,1.220
85,32.75,47.00,42.760562,44.500,3.398919,41.33,45.3725,0.0,3.34,0.486167,...,4.296574,13.0000,18.565,0.0,5.73,0.842271,0.710,0.722165,0.430,1.090
86,19.33,43.50,34.227771,35.500,4.889576,30.50,37.7500,0.0,14.50,3.995729,...,3.092094,14.7500,18.670,0.0,9.74,3.394125,3.100,1.792090,2.105,4.425
87,12.50,45.00,33.509729,34.125,4.850923,30.50,36.7500,0.0,13.05,4.450771,...,3.133564,14.6275,18.750,0.0,8.96,3.378479,3.085,1.787360,2.060,4.440
88,15.00,46.75,34.660583,35.000,5.315110,31.00,38.2500,0.0,13.44,4.200896,...,3.155015,14.2500,18.500,0.0,8.99,3.244396,3.000,1.630983,2.120,4.240

#### (iii) Standard Deviations and 90% Bootstrap Confidence Intervals

In [10]:
feature_std = feature_df.std()

feature_std

min1          9.624011
max1          4.207745
mean1         5.276431
median1       5.386624
std1          1.771282
1st_quart1    6.127846
3rd_quart1    5.031028
min2          0.000000
max2          5.059656
mean2         1.577908
median2       1.413545
std2          0.885875
1st_quart2    0.948434
3rd_quart2    2.131337
min3          2.954516
max3          4.819848
mean3         3.976754
median3       4.009687
std3          0.952011
1st_quart3    4.184148
3rd_quart3    4.153451
min4          0.000000
max4          2.181809
mean4         1.168268
median4       1.148591
std4          0.458612
1st_quart4    0.844919
3rd_quart4    1.555235
min5          6.121205
max5          5.773355
mean5         5.704025
median5       5.844368
std5          1.012358
1st_quart5    6.122142
3rd_quart5    5.563553
min6          0.046101
max6          2.533515
mean6         1.157222
median6       1.089858
std6          0.516968
1st_quart6    0.761542
3rd_quart6    1.526871
dtype: float64

In [11]:
# calculating 90% bootstrap confidence interval
def bootstrap_std_ci(data, n_bootstrap=10000, confidence=0.90):
    
    # Remove missing values
    data = data.dropna()
    
    bootstrap_stds = []

    # Creating 10,000 bootstrap samples
    for _ in range(n_bootstrap):
        sample = np.random.choice(
            data,
            size=len(data),
            replace=True
        )

        # Calculate standard deviation of each sample
        bootstrap_stds.append(np.std(sample, ddof=1))

    # Find the lower and upper percentiles
    alpha = 1 - confidence

    lower = np.percentile(
        bootstrap_stds,
        100 * (alpha / 2)
    )

    upper = np.percentile(
        bootstrap_stds,
        100 * (1 - alpha / 2)
    )

    return lower, upper

In [12]:
feature_df.isna().sum()

min1          1
max1          1
mean1         1
median1       1
std1          1
1st_quart1    1
3rd_quart1    1
min2          1
max2          1
mean2         1
median2       1
std2          1
1st_quart2    1
3rd_quart2    1
min3          1
max3          1
mean3         1
median3       1
std3          1
1st_quart3    1
3rd_quart3    1
min4          1
max4          1
mean4         1
median4       1
std4          1
1st_quart4    1
3rd_quart4    1
min5          1
max5          1
mean5         1
median5       1
std5          1
1st_quart5    1
3rd_quart5    1
min6          1
max6          1
mean6         1
median6       1
std6          1
1st_quart6    1
3rd_quart6    1
dtype: int64

In [13]:
feature_df[feature_df.isna().any(axis=1)]

,min1,max1,mean1,median1,std1,1st_quart1,3rd_quart1,min2,max2,mean2,...,std5,1st_quart5,3rd_quart5,min6,max6,mean6,median6,std6,1st_quart6,3rd_quart6
Instance,,,,,,,,,,,,,,,,,,,,,
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:

np.random.seed(42)

results = []

# Calculating the standard deviation and CI for all features
for feature in feature_df.columns:
    
    data = feature_df[feature]
    
    # Standard deviation
    std = data.std()
    
    # 90% bootstrap CI
    lower, upper = bootstrap_std_ci(data)
    
    results.append([
        std,
        lower,
        upper
    ])

#results
bootstrap_results = pd.DataFrame(
    results,
    index=feature_df.columns,
    columns=[
        "Standard Deviation",
        "90% CI Lower",
        "90% CI Upper"
    ]
)

bootstrap_results.round(4)

            Standard Deviation  90% CI Lower  90% CI Upper
min1                    9.6240        8.3307       10.8553
max1                    4.2077        3.1120        5.1249
mean1                   5.2764        4.6292        5.8330
median1                 5.3866        4.7175        5.9579
std1                    1.7713        1.5733        1.9507
1st_quart1              6.1278        5.5366        6.6166
3rd_quart1              5.0310        4.2033        5.7234
min2                    0.0000        0.0000        0.0000
max2                    5.0597        4.6230        5.4105
mean2                   1.5779        1.3965        1.7078
median2                 1.4135        1.2404        1.5455
std2                    0.8859        0.8048        0.9432
1st_quart2              0.9484        0.8324        1.0365
3rd_quart2              2.1313        1.9021        2.2996
min3                    2.9545        2.7589        3.1044
max3                    4.8198        4.0948        5.4324
mean3                   3.9768        3.3643        4.4744
median3                 4.0097        3.3955        4.5224
std3                    0.9520        0.7692        1.1308
1st_quart3              4.1841        3.5734        4.6821
3rd_quart3              4.1535        3.5212        4.6878
min4                    0.0000        0.0000        0.0000
max4                    2.1818        1.9717        2.3632
mean4                   1.1683        1.0792        1.2228
median4                 1.1486        1.0582        1.2038
std4                    0.4586        0.4225        0.4863
1st_quart4              0.8449        0.7761        0.8926
3rd_quart4              1.5552        1.4374        1.6280
min5                    6.1212        4.3676        7.5362
max5                    5.7734        4.7749        6.6126
mean5                   5.7040        4.4275        6.7680
median5                 5.8444        4.5463        6.9569
std5                    1.0124        0.8005        1.2049
1st_quart5              6.1221        4.7992        7.2247
3rd_quart5              5.5636        4.3711        6.5722
min6                    0.0461        0.0000        0.0789
max6                    2.5335        2.2640        2.7771
mean6                   1.1572        1.0648        1.2166
median6                 1.0899        0.9990        1.1503
std6                    0.5170        0.4785        0.5449
1st_quart6              0.7615        0.6944        0.8117
3rd_quart6              1.5269        1.4045        1.6031

#### (iv) Three Most Important Time-Domain Features

The mean, standard deviation, and maximum are the three most important time-domain features. The mean represents the average signal level, the standard deviation represents how much the signal chnages, and the maximum captures the peak values of the signal. So when they are all put together these features explain different characteristics of the time series that help understand the activities.

## 2. Linear Regression vs. Cubic Regression

### (a) Training RSS When the True Relationship is Linear

The cubic Regression is expected to have a lower or equal RSS because the linear model can fit inside the cubic model, so it can always perform at least as well as the linear model. Even though the true relationship is linear, X^2 and X^3 will pick up some random noise in these 100 points, which would push the training error down.

### (b) Test RSS When the True Relationship is Linear

The linear regression is expected to have a lower RSS because the true relationship is linear. The additional X^2 and X^3 in the cubic model has more flexibility and it would overfit into  random noise, which will cause overfitting. When the true relationship is linear, this overfitting increases the variance of the fitted model, which gives the cubic model a higher expected test error than the linear model.

### (c) Training RSS When the True Relationship is Nonlinear

The cubic regression is expected to have a training RSS less than or equal to that of the linear regression because the cubic model is more flexible, so it can fit the training observations at least as well as the linear model.

### (d) Test RSS When the True Relationship is Nonlinear

There is not enough information to determine which model will have the lower test RSS. 
If the true relationship is not linear(curve, cubic-like), the linear model has large bias, and the cubic model's lower bias outweighs its extra variance, so the cubic model has the lower test RSS.
If the true relationship is closer to linear than cubic, the bias removed by the cubic model is small compared with the variance it adds, so the linear model can still have the lower test RSS.